#!/usr/bin/env bash
# This script displays the content of the current directory
#+ In a list format
#+ only the part of the name after the first dash is displayed

var=$(ls)
for i in $var; do
  echo "$i" | cut -d '-' -f2
done